"""
strategicc/calibration/manifest.py  —  v3.9
----------------------------------------------
Generate a pre-filled RunManifest_calibrated.txt from calibration results.

The four rows that calibration can populate automatically are:
  TRANSITIONS_CSV       ← Transitions.csv
  TRANSITION_MULT_CSV   ← TransitionMultipliers.csv
  TRANSITION_SIZE_CSV   ← TransitionSizeDistribution.csv
  AgeFileName           ← age.tif

All other fields are left blank with # TODO: comments so the user
knows exactly what still needs to be filled manually.

Functions
---------
save_calibration_manifest  — write RunManifest_calibrated.txt
"""

from __future__ import annotations
from pathlib import Path
from datetime import datetime


def save_calibration_manifest(
    transitions_path: Path | None = None,
    temporal_path:    Path | None = None,
    size_dist_path:   Path | None = None,
    age_raster_path:  Path | None = None,
    out_path:         Path | None = None,
) -> Path:
    """
    Write a pre-filled RunManifest_calibrated.txt using paths from a
    calibration run.

    Fields that calibration populated are filled in automatically.
    Fields that require manual input are left blank with # TODO: comments.

    Parameters
    ----------
    transitions_path : path to Transitions.csv (from save_transitions_csv)
    temporal_path    : path to TransitionMultipliers.csv
    size_dist_path   : path to TransitionSizeDistribution.csv
    age_raster_path  : path to age.tif (from save_age_raster)
    out_path         : destination; defaults to
                       calibration_result/RunManifest_calibrated.txt

    Returns
    -------
    Path actually written to
    """
    from strategicc.calibration.paths import RUN_MANIFEST, CALIBRATION_DIR

    out_path = Path(out_path) if out_path is not None else RUN_MANIFEST
    out_path.parent.mkdir(parents=True, exist_ok=True)

    def _p(path: Path | None) -> str:
        """Return path as string, or empty string if None."""
        return str(path) if path is not None else ""

    def _flag(path: Path | None, key: str) -> str:
        """Return the correct feature toggle based on whether this was calibrated."""
        val = "True" if path is not None else "False"
        return f"{key:<30s} = {val}"

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    calibrated = []
    if transitions_path:   calibrated.append("Transitions.csv")
    if temporal_path:      calibrated.append("TransitionMultipliers.csv")
    if size_dist_path:     calibrated.append("TransitionSizeDistribution.csv")
    if age_raster_path:    calibrated.append("age.tif")

    header = f"""\
#================================================================
# STRATEGICC RunManifest_calibrated.txt
# Auto-generated by strategicc.calibration  [{now}]
#
# Fields marked  [calibration]  were filled automatically from
# your calibration run outputs.
# Fields marked  # TODO:  require manual input before running.
#
# Calibrated in this run:
{chr(10).join(f"#   ✓  {c}" for c in calibrated) if calibrated else "#   (none)"}
#================================================================

"""

    # ── Section 1: Initial Conditions ────────────────────────────────────────
    age_line = (
        f"AgeFileName               = {_p(age_raster_path)}"
        + ("  # [calibration]" if age_raster_path else "  # TODO: path to age raster, or leave blank to use AGE_INITIAL_CSV")
    )

    s1 = f"""\
#================================================================
# SECTION 1 — INITIAL CONDITIONS (SPATIAL)
#================================================================
StateClassFileName        =   # TODO: path to initial LULC raster (e.g. 2022.tif)
{age_line}

FetchInitialStateClassFromZip  = False  # TODO: set True to pull initial raster from LULC zip
LULCZipPath                    =        # TODO: path to historical LULC zip (if above = True)
InitialStateClassYear          =        # TODO: year to extract from zip

"""

    # ── Section 2: CSV Inputs ─────────────────────────────────────────────────
    def _csv_line(var: str, path: Path | None, todo_hint: str) -> str:
        if path is not None:
            return f"{var:<35s} = {path}  # [calibration]"
        return f"{var:<35s} =   # TODO: {todo_hint}"

    s2 = f"""\
#================================================================
# SECTION 2 — MULTI-ROW CSV INPUTS
#================================================================
STATE_CLASSES_CSV                   =   # TODO: path to StateClasses.csv
{_csv_line("TRANSITIONS_CSV", transitions_path, "path to Transitions.csv")}
SPATIAL_MULT_CSV                    =   # TODO: path to TransitionSpatialMultipliers.csv (not calibratable from rasters alone)
{_csv_line("TRANSITION_MULT_CSV", temporal_path, "path to TransitionMultipliers.csv")}
TRANSITION_TYPE_CSV                 =   # TODO: path to Transition Type.csv
ECOSYSTEM_SERVICES_CSV              =   # TODO: path to EcosystemServices.csv — service values per class
AGE_INITIAL_CSV                     =   # TODO: path to InitialAge.csv (if not using AgeFileName above)
{_csv_line("TRANSITION_SIZE_CSV", size_dist_path, "path to TransitionSizeDistribution.csv")}
TRANSITION_ADJACENCY_SETTING_CSV    =   # TODO: path to Transition Adjacency Setting.csv (optional)
TRANSITION_ADJACENCY_MULT_CSV       =   # TODO: path to Transition Adjacency Multipliers.csv (optional)
TERMINOLOGY_CSV                     =   # TODO: path to Terminology.csv (optional)
MULT_DIR                            =   # TODO: folder or .zip containing spatial multiplier rasters
OUT_DIR                             =   # TODO: path to simulation output folder

"""

    # ── Section 3: Run Control ────────────────────────────────────────────────
    s3 = """\
#================================================================
# SECTION 3 — RUN CONTROL
#================================================================
START_YEAR     =     # TODO: int — e.g. 2022
N_TIMESTEPS    =     # TODO: int — number of years to simulate
N_ITERATIONS   =     # TODO: int — number of Monte Carlo iterations (e.g. 20)
RNG_SEED       = 42  #int
AREA_UNIT      = ha  #str  (ha | km2 | px)

"""

    # ── Section 4: Feature Toggles ────────────────────────────────────────────
    s4 = f"""\
#================================================================
# SECTION 4 — FEATURE TOGGLES
#================================================================
USE_ADJACENCY        = False  # TODO: set True if TransitionAdjacency CSVs are filled
USE_SPATIAL_MULT     = False  # TODO: set True if SPATIAL_MULT_CSV and MULT_DIR are filled
{_flag(temporal_path,   "USE_TRANS_MULTIPLIER")}{"  # [calibration]" if temporal_path else ""}
USE_SEEA             = True   # set False to skip ecosystem accounting
{_flag(age_raster_path, "USE_AGE")}{"  # [calibration]" if age_raster_path else ""}
SAVE_AGE_RASTERS     = True

"""

    # ── Section 5–6: Output Options ───────────────────────────────────────────
    s5 = """\
#================================================================
# SECTION 5 — OUTPUT OPTIONS (NON-SPATIAL)
#================================================================
SummaryOutputSC            = Yes  #bool
SummaryOutputSCTimesteps   = 1    #int
SummaryOutputTR            = Yes  #bool
SummaryOutputTRTimesteps   = 1    #int

#================================================================
# SECTION 6 — OUTPUT OPTIONS (SPATIAL)
#================================================================
RasterOutputSC                       = Yes  #bool
RasterOutputSCTimesteps              = 1    #int
RasterOutputAge                      = Yes  #bool
RasterOutputAgeTimesteps             = 1    #int
RasterOutputTransitionEvents         = Yes  #bool
RasterOutputTransitionEventTimesteps = 1    #int

"""

    content = header + s1 + s2 + s3 + s4 + s5

    out_path.write_text(content, encoding="utf-8")
    print(f"  Saved: {out_path}")
    return out_path
